PYTHONPATH=. python3 evalute/predict.py   /home/yeep/project/py/deeplearning/AL-ACDC/Config/al-isic-0.1/fulllabeled.yml  /home/yeep/project/py/deeplearning/AL-ACDC/data/ISIC/test/ /home/yeep/project/py/deeplearning/AL-ACDC/EXP/ISICPlot/LeastConfidence/checkpoint/c1_best0.8423.pt  /home/yeep/project/py/deeplearning/AL-ACDC/EXP/ISICPlot/LeastConfidence/out_dir/c1 2
PYTHONPATH=. python3 evalute/predict.py   /home/yeep/project/py/deeplearning/AL-ACDC/Config/al-isic-0.1/fulllabeled.yml  /home/yeep/project/py/deeplearning/AL-ACDC/data/ISIC/test/ /home/yeep/project/py/deeplearning/AL-ACDC/EXP/ISICPlot/LeastConfidence/checkpoint/c2_best0.8539.pt  /home/yeep/project/py/deeplearning/AL-ACDC/EXP/ISICPlot/LeastConfidence/out_dir/c2 2
PYTHONPATH=. python3 evalute/predict.py   /home/yeep/project/py/deeplearning/AL-ACDC/Config/al-isic-0.1/fulllabeled.yml  /home/yeep/project/py/deeplearning/AL-ACDC/data/ISIC/test/ /home/yeep/project/py/deeplearning/AL-ACDC/EXP/ISICPlot/LeastConfidence/checkpoint/c3_best0.8654.pt  /home/yeep/project/py/deeplearning/AL-ACDC/EXP/ISICPlot/LeastConfidence/out_dir/c3 2

PYTHONPATH=. python3 evalute/predict.py   /home/yeep/project/py/deeplearning/AL-ACDC/Config/al-isic-0.1/fulllabeled.yml  /home/yeep/project/py/deeplearning/AL-ACDC/data/ISIC/test/ /home/yeep/project/py/deeplearning/AL-ACDC/EXP/ISICPlot/Coreset/checkpoint/c0_best0.7851.pt /home/yeep/project/py/deeplearning/AL-ACDC/EXP/ISICPlot/Coreset/out_dir/c0 2
PYTHONPATH=. python3 evalute/predict.py   /home/yeep/project/py/deeplearning/AL-ACDC/Config/al-isic-0.1/fulllabeled.yml  /home/yeep/project/py/deeplearning/AL-ACDC/data/ISIC/test/ /home/yeep/project/py/deeplearning/AL-ACDC/EXP/ISICPlot/Coreset/checkpoint/c1_best0.8607.pt  /home/yeep/project/py/deeplearning/AL-ACDC/EXP/ISICPlot/Coreset/out_dir/c1 2
PYTHONPATH=. python3 evalute/predict.py   /home/yeep/project/py/deeplearning/AL-ACDC/Config/al-isic-0.1/fulllabeled.yml  /home/yeep/project/py/deeplearning/AL-ACDC/data/ISIC/test/ /home/yeep/project/py/deeplearning/AL-ACDC/EXP/ISICPlot/Coreset/checkpoint/c2_best0.8686.pt  /home/yeep/project/py/deeplearning/AL-ACDC/EXP/ISICPlot/Coreset/out_dir/c2 2
PYTHONPATH=. python3 evalute/predict.py   /home/yeep/project/py/deeplearning/AL-ACDC/Config/al-isic-0.1/fulllabeled.yml  /home/yeep/project/py/deeplearning/AL-ACDC/data/ISIC/test/ /home/yeep/project/py/deeplearning/AL-ACDC/EXP/ISICPlot/Coreset/checkpoint/c3_best0.8765.pt /home/yeep/project/py/deeplearning/AL-ACDC/EXP/ISICPlot/Coreset/out_dir/c3 2


PYTHONPATH=. python3 evalute/predict.py   /home/yeep/project/py/deeplearning/AL-ACDC/Config/al-isic-0.1/fulllabeled.yml  /home/yeep/project/py/deeplearning/AL-ACDC/data/ISIC/test/ /home/yeep/project/py/deeplearning/AL-ACDC/EXP/ISICPlot/KMeans/checkpoint/c0_best0.7851.pt /home/yeep/project/py/deeplearning/AL-ACDC/EXP/ISICPlot/KMeans/out_dir/c0 2
PYTHONPATH=. python3 evalute/predict.py   /home/yeep/project/py/deeplearning/AL-ACDC/Config/al-isic-0.1/fulllabeled.yml  /home/yeep/project/py/deeplearning/AL-ACDC/data/ISIC/test/ /home/yeep/project/py/deeplearning/AL-ACDC/EXP/ISICPlot/KMeans/checkpoint/c1_best0.8657.pt  /home/yeep/project/py/deeplearning/AL-ACDC/EXP/ISICPlot/KMeans/out_dir/c1 2
PYTHONPATH=. python3 evalute/predict.py   /home/yeep/project/py/deeplearning/AL-ACDC/Config/al-isic-0.1/fulllabeled.yml  /home/yeep/project/py/deeplearning/AL-ACDC/data/ISIC/test/ /home/yeep/project/py/deeplearning/AL-ACDC/EXP/ISICPlot/KMeans/checkpoint/c2_best0.8656.pt  /home/yeep/project/py/deeplearning/AL-ACDC/EXP/ISICPlot/KMeans/out_dir/c2 2
PYTHONPATH=. python3 evalute/predict.py   /home/yeep/project/py/deeplearning/AL-ACDC/Config/al-isic-0.1/fulllabeled.yml  /home/yeep/project/py/deeplearning/AL-ACDC/data/ISIC/test/ /home/yeep/project/py/deeplearning/AL-ACDC/EXP/ISICPlot/KMeans/checkpoint/c3_best0.8729.pt /home/yeep/project/py/deeplearning/AL-ACDC/EXP/ISICPlot/KMeans/out_dir/c3 2

